# Generated by Django 5.0.4 on 2024-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_libro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devolucion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
